### ISSUE TITLE
Scopes don't support UUIDs

### ISSUE THREAD

**Issue by sudhirj** [envato/double_entry#100]
Because of the 23 character limit, it looks like it's impossible to support UUIDs as scopes - this is quite odd because they make excellent scopes. Can we do something about this?

**Comment by spickermann** [comment]
@sudhirj : You can change the limits to whatever suits your application. Just update the limits in the database and set the new limits in the configuration. This PR https://github.com/envato/double_entry/pull/46 might be interesting in this context.

**Comment by sudhirj** [comment]
Good point. I've just got a separate model storing my metadata anyway, so I'm using smaller integers converted to strings (not ideal, but basically any string identifier should work). Will probably move to base36 encoding later, that should make things a lot more efficient.
