### ISSUE TITLE
Accounting rules

### ISSUE THREAD

**Issue by amicheals** [envato/double_entry#106]
What do you mean by this program does not enforce accounting rules?

**Comment by orien** [comment]
There are many rules that you'll want to implement when building your accounting system. For instance if building a [balance sheet](https://en.wikipedia.org/wiki/Balance_sheet) you'll need to create DoubleEntry accounts in the Asset and Liability categories. Here DoubleEntry doesn't assist by enforcing these categories; it only provides the basic bookkeeping building blocks of accounts and transfers. As a developer you'll have to come up with the accounts you need your case and ensure they're correctly categorised.

**Comment by laptopmutia** [comment]
@orien I kinda confused with the transfers

by transfers did it means adding something to accounts journal entry?
