### ISSUE TITLE
Use bigint for all IDs

### ISSUE THREAD

**Issue by sudhirj** [envato/double_entry#113]
`integer` is currently being used, and it took our project only a few months to hit more transactions than the 32 bit int supports. I'd suggest changing all IDs to `bigint`.

**Comment by sudhirj** [comment]
The problem was actually on the `amount` and `balance` columns. Over a period of time accounts tend to accumulate a lot of money, especially when used in currencies that a low value, like the Yen or the Lira, although I faced the issue with the Rupee, which is less than one order of magnitude lower than the Dollar. Here are my migrations:

**Comment by orien** [comment]
Good call @sudhirj. I think this schema adjustment is one people can make depending on the specific requirements of their project. For some a 32 bit int will be sufficient, for others it won't.

I look at adding that to the getting started section in the read me so developers consciously make that decision.
