### ISSUE TITLE
Importing Legacy Transactions

### ISSUE THREAD

**Issue by drush** [envato/double_entry#169]
Does anyone have a good pattern for importing legacy transactions into DE? This would require recording a transfer at a specific time in the past.  

It looks like there are two options:

1) Modifications to transfer/process/create_lines in order to override default dates

2) Override Time.now or AR setters for created_at/updated_at in a block outside the transfer creation.

Any ideas, thoughts, gists welcome.

**Comment by drush** [comment]
@orien Do you have any thoughts on this?

**Comment by orien** [comment]
hi @drush, I can't say I've ever done this. I wonder if the `DoubleEntry.transfer` method should accept a timestamp option for this usecase.

**Comment by FUT** [comment]
@drush Hello! What solution did you choose? I am in the same situation currently :)

**Comment by drush** [comment]
You should test this approach thoroughly for your use case, but you can try time travel: https://github.com/travisjeffery/timecop to set the time of the transaction.  Your intermediate balances will all have to be recalculated if you do this, so beware.

**Comment by orien** [comment]
Thanks for sharing @drush.

I'll close this issue now.
