### ISSUE TITLE
New release with fix of details requirements?

### ISSUE THREAD

**Issue by arrowcircle** [envato/double_entry#195]
Hey! It looks like latest rubygems version does not include fixes for optional details requirement.
Could you please release new version?

Is current beta state is usable?

**Comment by swrobel** [comment]
I'm using the beta version in production and it seems stable to me. The latest beta (2.0.0.beta5) has the optional detail association.

**Comment by orien** [comment]
Version 2.0.0 is now available: https://rubygems.org/gems/double_entry/versions/2.0.0
