### ISSUE TITLE
Storing chart of account in database rather than an initializers file

### ISSUE THREAD

**Issue by nathanclark** [envato/double_entry#209]
I want to allow users to manage their own chart of accounts rather than needing a developer to update source code. Is there a way to forgo the initializer file and read accounts from a database table?

**Comment by ricobl** [comment]
Hey @nathanclark, `double_entry` wasn't built with that in mind, I believe we'd have to rejig things around to make it work.

**Comment by nathanclark** [comment]
Thanks for the quick reply!
