### ISSUE TITLE
Version 2.0 release

### ISSUE THREAD

**Issue by achhetr** [envato/double_entry#211]
Is there anything blocking for version 2.0 release. It has been more than a year for beta version.

**Comment by jeremycw** [comment]
I agree. It looks like Ruby 3 support just got added so it seems like a good time for a release. Are people hand wringing over a 2.0.0 release? I feel like most people have been forced to run of a git commit instead of a release at this point anyway. It seems like any release is better than nothing at this point.

**Comment by achhetr** [comment]
It would be great to have official release, happy to help if anything blocks it :)

**Comment by daande** [comment]
@orien / @asellitt we are about to start using this gem for a project.  I was wondering if we can get a 2.0 release cut that way we do not have to pin to specific commit?

**Comment by asellitt** [comment]
I think you're right. Looking over the recently merged PRs, it looks like theres quite a bit of change. I'll try to find some time next week to get a proper change log written up, and then see if i can remember how to release a new version

**Comment by daande** [comment]
@asellitt my team is picking up this gem to use at our company.  If you want some support at getting a release out email me at dane@wonolo.com

**Comment by daande** [comment]
@orien / @asellitt any update on this?

**Comment by asellitt** [comment]
Sorry, I no longer work at envato and cannot help you with this.

**Comment by daande** [comment]
> Sorry, I no longer work at envato and cannot help you with this.

We are hiring at Wonolo (remote) email me your resume if you want dane@wonolo.com!

**Comment by swrobel** [comment]
@stevend @scottyp-env @ricobl any thoughts here?

**Comment by swrobel** [comment]
@orien?

**Comment by orien** [comment]
Sorry for the delay folks. We have this task in our backlog, I'll try and get it prioritised.

**Comment by jmatraszek** [comment]
Hi @orien, is there any timeline when we can expect 2.0 release? Thanks!

**Comment by orien** [comment]
Thanks for your patience everyone.

Version 2.0.0 has been released and is available on rubygems.org: https://rubygems.org/gems/double_entry/versions/2.0.0

**Comment by daande** [comment]
@orien can you take a look at this PR ?

https://github.com/envato/double_entry/pull/213#issuecomment-1372645467
