### ISSUE TITLE
Account Scope initializer not compatible with Spring Preloader (for development)

### ISSUE THREAD

**Issue by jeffnappi** [envato/double_entry#75]
The account scope initialization using ActiveRecordScopeFactory currently takes a reference to the scoped class at startup. This is [not compatible with the Rails Spring loader](https://github.com/rails/spring#class-reloading) which provides a dramatic speedup during app development.

I understand that this may be by design, but I'd like to discuss potential workarounds at least for development.

**Comment by orien** [comment]
Good to hear you've resolved your issue @jeffnappi. Do you have recommendations that you'd like implemented in DoubleEntry?
