### ISSUE TITLE
Lack of negative_only account option

### ISSUE THREAD

**Issue by jeffnappi** [envato/double_entry#76]
We have the positive_only account option, but lack a negative_only option.

For our use-case, a negative_only account option and complementary validation would be quite beneficial.

**Comment by jeffnappi** [comment]
@orien thanks for resolving this! I thought I'd get it reported and would have gladly assisted with the feature. Looking forward to seeing this in the next release.

**Comment by orien** [comment]
Version 0.10.0 has just been released.
